sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO="django>=1.8,<1.9"
  - DJANGO="django>=1.9,<1.10"
install:
  - pip install "$DJANGO"
  - pip install .
  - pip install -r testapp/requirements.txt
script:
  – python -Wall testapp/manage.py test
